-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgB1UO8xuFjve6pHiC
cZahi4b7CfInGBHmzZdgh/RLvCOgCgYIKoZIzj0DAQehRANCAATdDmpFzwnv6X2d
JefG/dSBpxNyGy18EZaYMJ03cGRmJLy9Y7vduApgbrplWM5qyWLE/dOJy5MB5Zdw
zXlxq3SV
-----END PRIVATE KEY-----