# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Clay_new' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'KakaoSDKCommon'
pod 'KakaoSDKAuth'
pod 'KakaoSDKUser'
  # Pods for Clay_new

  target 'Clay_newTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Clay_newUITests' do
    # Pods for testing
  end

end
